const discussions = [
  { title: 'What is a must feature of a SaaS product?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  {
    title: "Ah, let's spread the word! The main target audience of your awesome product/startup ?! 🎯🚀",
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  { title: 'What is your favorite SaaS product and why?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Have you ever heard of UX Writing?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Slowly grinding and now I have 200 followers', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Do you have any tips when inputting prompts into Chat GPT?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'What stops you right now to grow faster?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'How do you discover or search for new tools and products? ', content: '', author: '64cbabeef8b08fb5ba94912d' },
  {
    title: "Looking for new connections. Let's add each other on LinkedIn!",
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  {
    title: 'Share your favorite inspirational quote that motivates you every day.',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  { title: "Exciting News! We're launching @Build Chatbot tomorrow!", content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: "What's the most used tool in your workflow?", content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: "What's the best launch tip you've ever heard?", content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: '5 Questions Your Bio Needs To Answer', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: "What's your favorite way to unwind after a long day?", content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Your top-3 books every founder should read?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  {
    title: 'Honest replies🙏what marketing steps you will take after launching the product on PH?',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  {
    title: 'Looking for honest feedback: can you review our Coming Soon page?',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  { title: "What's the best lead generation strategy for b2b companies?", content: '', author: '64cbabeef8b08fb5ba94912d' },
  {
    title: 'Where do you sell your product? Have you ever try indieproduct marketplace?',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  {
    title: "What's the number one reason people quit working on personal projects?",
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  { title: 'Do you use Notion for team collaboration & projects ?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'How do you find your potential users?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'What qualities a good co-founder for a startup? 🚀🤝', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Validating a startup idea', content: '', author: '64cbabeef8b08fb5ba94912d' },
  {
    title: 'Anyone working on developing AI-based language learning platforms?',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  {
    title: "What's the most valuable skill you've learned in your career?",
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  {
    title: 'Is it difficult for you to find a designer to create a promotional video for your product?',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  { title: 'How to get users to spend more (without feeling sleazy):', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'How long do you prepare before launching your product?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  {
    title: 'What are some of the biggest challenges facing AI product development today?',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  {
    title: 'Launched with just 2 days of prep and ranked #1 Product of the Day and #3 Product of the Week [AMA]',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
  { title: 'Is it time to remove [ AI ] from our brand names?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Best alternative to good reads?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Launching without social network?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Have you had any successful PH launches? Share them 👋🏼', content: '', author: '64cbabeef8b08fb5ba94912d' },
  { title: 'Advice for non-technical founders?', content: '', author: '64cbabeef8b08fb5ba94912d' },
  {
    title: 'Thoughts on Twitter rebrand? Also, do you call it X or Twitter still?',
    content: '',
    author: '64cbabeef8b08fb5ba94912d',
  },
];

module.exports = {
  discussions,
};
